backend:
  name: git-gateway

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - label: "Sekcijos"
    name: "pages"
    files:
      - label: "Apie mus"
        name: "about"
        file: "content/cms.json"
        fields:
          - {label: Antraštė, name: about-us-header, widget: string}
          - {label: Tekstas, name: about-us-text, widget: string}